### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by swapnilghadge2390** [adityasharat/proteus-demo#1]
Hey @adityasharat , Please let me know where i can find user.json and other layout json file. Thanks in advance.

**Comment by adityasharat** [comment]
Hey @swapnilghadge2390 
It is better to check out the parent project [proteus](https://github.com/flipkart-incubator/proteus) now. It has more comprehensive examples. Follow the instructions in the readme. You can find all the files [here](https://github.com/flipkart-incubator/proteus/tree/master/data)

**Comment by swapnilghadge2390** [comment]
Thamn
