### ISSUE TITLE
The code is not compatible with 5.0.0-rc12

### ISSUE THREAD

**Issue by sisogit** [adityasharat/proteus-demo#2]
Unable to compile the demo code with The code is not compatible with 5.0.0-rc12 version.
Most of the classes are mismatching.

Request to update.

**Comment by adityasharat** [comment]
It seems like a new version of proteus needs to be released to address this. This will take time. 

If you simply want to evaluate proteus please use the demo included in [the repo](https://github.com/flipkart-incubator/proteus)

if you want to use it for development consider cloning the repo locally and using it as a module.

This is an interim workaround while we fix this.

**Comment by adityasharat** [comment]
fixed by #3
